deployment:
    tasks:
        - export DEPLOYPATH=/home/fhsnzrgr/dev.fhs-news.org/
        - /usr/bin/scp -r css/ $DEPLOYPATH
        - /usr/bin/scp -r fonts/ $DEPLOYPATH
        - /usr/bin/scp -r html/ $DEPLOYPATH
        - /usr/bin/scp -r img/ $DEPLOYPATH
        - /usr/bin/scp -r js/ $DEPLOYPATH
        - /usr/bin/scp -r json/ $DEPLOYPATH
        - /usr/bin/scp -r modules/ $DEPLOYPATH
        - /usr/bin/scp -r themes/ $DEPLOYPATH
        - /usr/bin/scp 404.html $DEPLOYPATH
        - /usr/bin/scp favicon.ico $DEPLOYPATH
        - /usr/bin/scp humans.txt $DEPLOYPATH
        - /usr/bin/scp index.html $DEPLOYPATH
        - /usr/bin/scp robots.txt $DEPLOYPATH